### PR TITLE
Add 2FA code option when logging in

### PR DESCRIPTION
**Pull request by simonlerpard**
Adding the possibility to login with 2-factor authentication enabled on
the SSH server. E.g. by using Google Authenticator (TOTP)

Partly solves #8

### CODE REVIEW

**Comment by simonlerpard** [comment]
I'm really not a front-end guy. So I just added the 2FA field. But maybe we would want to enable the field by a button switch with the text "Use 2FA" or something. But that's totally up to you, I'm pretty satisfied as it turned out now. For me 2FA is a minimum requirement when using password-based authentication towards an exposed SSH server, and I really liked your project. I was thinking of doing something similar, but then I found this project.

Thanks for your efforts, I really hope this could be something bigger. PiVPN is such a nice tool, and a simple GUI is making it even nicer!

**Comment by WeeJeWel** [comment]
Hey, thanks! Two questions:

1. Can you share screenshots/video of the login screen?
2. Does this mean that the 2FA input field is always visible, even if it isn't enabled? If yes, then that's a no-go.

**Comment by simonlerpard** [comment]
1. It looks like this:
image

2. I'll update the PR soon and fix so it must be enabled by config, otherwise I wont show it.

**Comment by simonlerpard** [comment]
Problem solved, it's now controllable through the ENABLE_2FA environment variable. It's disabled by default.

Here's a short video demonstrating how it works
https://user-images.githubusercontent.com/11946823/116490615-196cfb00-a898-11eb-81f8-898dc87d0bb6.mp4

**Comment by WeeJeWel** [comment]
Hm I guess that works but it's not very elegant. Especially not when allowing multiple users to log in.

How about making the field appear dynamically? Like all websites do with 2FA.

**Comment by simonlerpard** [comment]
I agree, that would be really neat. But that's quite hard to accomplish in a nice way though...  

We don't know which authentication methods the server supports until we actually try them. (Sometimes it helps to force the client to try authMethod=none, but the server isn't required to answer what methods it supports, so that's not a reliable solution)

And to just try each auth method one by one (until we have a success), is also very bad. Since the server will log those failed login attempts as failed, and that might get your IP banned if you're running e.g. fail2ban (which you should).

**Review by WeeJeWel — APPROVED** [review]

**Pull request merged**
